name: nomadnetshield
description: Flutter VPN based on OpenVPN Library.
publish_to: "none"

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  get: ^4.6.6
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
